In [28]:
import numpy as np
import pandas as pd

In [29]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [30]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [31]:

time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [32]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [33]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# **Working with Dates**

In [34]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [35]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

### **1. Extract year**

In [36]:
date['date_year'] = date['date'].dt.year
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

### **2. Extract Month**

In [37]:
date['date_year'] = date['date'].dt.year
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

### **3.Month Name**

In [38]:
date['date_month_name'] = date['date'].dt.month_name()
date.head()

        date  product_id  city_id  orders  date_year date_month_name
0 2019-12-10        5628       25       3       2019        December
1 2018-08-15        3646       14     157       2018          August
2 2018-10-23        1859       25       1       2018         October
3 2019-08-17        7292       25       1       2019          August
4 2019-01-06        4344       25       3       2019         January

### **4.Extract days**

In [39]:
date['date_day'] = date['date'].dt.day
date.head()

        date  product_id  city_id  orders  date_year date_month_name  date_day
0 2019-12-10        5628       25       3       2019        December        10
1 2018-08-15        3646       14     157       2018          August        15
2 2018-10-23        1859       25       1       2018         October        23
3 2019-08-17        7292       25       1       2019          August        17
4 2019-01-06        4344       25       3       2019         January         6

### **5.day of week**

In [40]:
date['date_dow'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,December,10,1
1,2018-08-15,3646,14,157,2018,August,15,2
2,2018-10-23,1859,25,1,2018,October,23,1
3,2019-08-17,7292,25,1,2019,August,17,5
4,2019-01-06,4344,25,3,2019,January,6,6

### **6.day of week - name**

In [41]:

date['date_dow_name'] = date['date'].dt.day_name()
date.drop(columns=['product_id','city_id','orders']).head()

        date  date_year date_month_name  date_day  date_dow date_dow_name
0 2019-12-10       2019        December        10         1       Tuesday
1 2018-08-15       2018          August        15         2     Wednesday
2 2018-10-23       2018         October        23         1       Tuesday
3 2019-08-17       2019          August        17         5      Saturday
4 2019-01-06       2019         January         6         6        Sunday

### **is weekend?**

In [43]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,December,10,1,Tuesday,0
1,2018-08-15,2018,August,15,2,Wednesday,0
2,2018-10-23,2018,October,23,1,Tuesday,0
3,2019-08-17,2019,August,17,5,Saturday,1
4,2019-01-06,2019,January,6,6,Sunday,1

### **Extract week of the year**

In [45]:
date['date_week'] = date['date'].dt.isocalendar().week
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,December,10,1,Tuesday,0,50
1,2018-08-15,2018,August,15,2,Wednesday,0,33
2,2018-10-23,2018,October,23,1,Tuesday,0,43
3,2019-08-17,2019,August,17,5,Saturday,1,33
4,2019-01-06,2019,January,6,6,Sunday,1,1

### **Extract Quarter**

In [46]:
date['quarter'] = date['date'].dt.quarter
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,January,6,6,Sunday,1,1,1

### **Extract Semester**

In [48]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,January,6,6,Sunday,1,1,1,1

### **Extract Time elapsed between dates**

In [49]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 4, 13, 13, 22, 57, 530501)

In [50]:
today - date['date']

0     2316 days 13:22:57.530501
1     2798 days 13:22:57.530501
2     2729 days 13:22:57.530501
3     2431 days 13:22:57.530501
4     2654 days 13:22:57.530501
                 ...
995   2744 days 13:22:57.530501
996   2685 days 13:22:57.530501
997   2533 days 13:22:57.530501
998   2598 days 13:22:57.530501
999   2372 days 13:22:57.530501
Name: date, Length: 1000, dtype: timedelta64[ns]

In [51]:
(today - date['date']).dt.days

0      2316
1      2798
2      2729
3      2431
4      2654
       ...
995    2744
996    2685
997    2533
998    2598
999    2372
Name: date, Length: 1000, dtype: int64

In [58]:
#Montsh passed
date['months_passed'] = (
    (today.year - date['date'].dt.year) * 12 +
    (today.month - date['date'].dt.month)
)
date.head()

,date,product_id,city_id,orders,date_year,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester,months_passed
0,2019-12-10,5628,25,3,2019,December,10,1,Tuesday,0,50,4,2,76
1,2018-08-15,3646,14,157,2018,August,15,2,Wednesday,0,33,3,2,92
2,2018-10-23,1859,25,1,2018,October,23,1,Tuesday,0,43,4,2,90
3,2019-08-17,7292,25,1,2019,August,17,5,Saturday,1,33,3,2,80
4,2019-01-06,4344,25,3,2019,January,6,6,Sunday,1,1,1,1,87

In [59]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [62]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [63]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [64]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

### **Extract Time part**

In [65]:

time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

### **Time difference**

In [66]:
today - time['date']

0     4502 days 12:32:57.530501
1     4366 days 13:42:57.530501
2     4852 days 13:01:57.530501
3     4154 days 12:51:57.530501
4     4551 days 14:11:57.530501
                 ...
995   5141 days 12:32:57.530501
996   4462 days 14:08:57.530501
997   4927 days 13:45:57.530501
998   5043 days 13:48:57.530501
999   4315 days 13:57:57.530501
Name: date, Length: 1000, dtype: timedelta64[ns]

In [67]:

# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.890180e+08
1      3.772718e+08
2      4.192597e+08
3      3.589519e+08
4      3.932575e+08
           ...
995    4.442276e+08
996    3.855677e+08
997    4.257424e+08
998    4.357649e+08
999    3.728663e+08
Name: date, Length: 1000, dtype: float64

In [68]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.483633e+06
1      6.287863e+06
2      6.987662e+06
3      5.982532e+06
4      6.554292e+06
           ...
995    7.403793e+06
996    6.426129e+06
997    7.095706e+06
998    7.262749e+06
999    6.214438e+06
Name: date, Length: 1000, dtype: float64

In [69]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      108060.549314
1      104797.715981
2      116461.032647
3       99708.865981
4      109238.199314
           ...
995    123396.549314
996    107102.149314
997    118261.765981
998    121045.815981
999    103573.965981
Name: date, Length: 1000, dtype: float64